brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
wrap_comments = true
edition = "2021"
fn_single_line = true
force_multiline_blocks = true
max_width = 79
unstable_features = true
