[package]
name = "voltgtd"
description = "Volatus' GTD utility editor"
authors = ["Volatus"]
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26"
regex = "1.8"
lazy_static = "1.4"
